[package]
name = "ruxl"
version = "0.1.0"
authors = ["Yihong Zhang <yz489@cs.washington.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
rand = "0.8.4"